name: Continuous Deployment

on:
  push:
    tags:
      - v*

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  publish:
    name: Publish on Netlify
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
    - name: Check out
      uses: actions/checkout@master
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --build
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}